name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      AWS_S3_BUCKET: todolist-1
      AWS_ACCESS_KEY_ID: AKIA2M72C4K3LN72TRR5
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: eu-north-1
      AWS_ROLE_TO_ASSUME: arn:aws:iam::715099660982:role/CICD-deploy


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install -r requirements.txt

#    - name: Debug
#      run: |
#        echo "AWS_REGION: $AWS_REGION"
#        echo "AWS_ROLE_TO_ASSUME: $AWS_ROLE_TO_ASSUME"

#    - name: Assume IAM Role
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-region: ${{ env.AWS_REGION }}
#        role-to-assume: ${{env.AWS_ROLE_TO_ASSUME }}
#        role-duration-seconds: 900

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        aws-key: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret: ${{ env.AWS_SECRET_ACCESS_KEY }}
        src: '.'  
        dest: 's3://todolist-1/tasks/'

  deploy:
    runs-on: ubuntu-latest

    needs: build

    env:
      AWS_ACCESS_KEY_ID: AKIA2M72C4K3LN72TRR5
      AWS_SECRET_ACCESS_KEY: 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
      SSH_PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAl6z3TgXjjTQJvdEiNksv+wJE5/ngvulxTjaU6KTGRF98n6Li
        7CKAG2IpVQaUJWnkPpL1svlZu86OXTxVeBbscyfhoy9syqw0BMeCVBlJVHx+hqkM
        cuy7dcJORYgon69zHq+UDk/LHhVxezHanY4rgptKm9330lO0loO8edm7DQm/imTR
        j0ow1Q/tt571ce6FBsJUfbgigtjGOsT/0FylAuckfcPAT3g6mKcSmTJ94ctQhr43
        9r3c/L1ly06z3fqlCPmZG56AeRTCNf4WkjtK+bQUob20kiQckkx+MiBSfTyXgCH0
        mLvPDCL0XiaJSPeiiy22wCNu9JJd8t2ypYTGHwIDAQABAoIBAQCH8VP6j1ajMVfl
        1HK4fO01KZR+4jxogCy4sD0Iwt6dW4QERGbkxAtT/8gR2AKiAeW7m9YxokGmDX0V
        3cSxDMLCd6VJsHDuuicpfXO3Uq6h1a9FnHB29O0Tn6KtuVrHvOYOQ8oMhcIEZa2/
        gDBz9H/U4MCfMPQ0hCegm9Qq1lZLWOcIrtZwEfF5fHlYkJ5nNejLAo6B9u5BH4BU
        lBBTgyxUqrYjB+WZHnBVODb9/Upr4UCwwJxYbePaDRaoYzzlSoHXgI48DN2Jew0b
        Pqvx+rvX3AogK2R6Vi0tuS1oBNMVyqpYeuDuWBZGy7GUXCH71OoLJay9hKizvBKa
        20UovoIBAoGBAMoETzY1MaZ/FaGJ6QmY6ak9k4+swo1Us8A2+CHCJqJQ5mD48WRD
        lcTFV1p7LpXOM/k73VDOGgMbwmY1HaQn553GC/GynbvjZkmyRn8xwvSrvWO/zriQ
        ua1ZfKdQh2Qmd9kcWKTDbZZkWAdos9D7ktQ5LbspUl82kE4gzW7eovsfAoGBAMA0
        4tvUFzeqnG4XDD29f+IxX8iwP6aEZmrRFxSP0bXMgEP9DHGZFD9AtK1s8BQ6tl1u
        6mqn9Pqa88B6GmSPWFU3t5dBfHdGvN0RK35/PaUqK3O/j+Ak8z8uZOH3whXsH3gU
        57sRO0lLuXk3VmyyATUEpXdsiQ/hRZDBdqUG79UBAoGBAMmvFboDz2bvF5Rnz/1h
        6V2qeSiGjNF2z+JFvuJNKC8C343O24iDJQIHFtfhhTfQXvkjuCeVLEkQLLvHqaka
        odVVRNVvwqQzOgq3bkRMVNvancD5XJPNAWK8pYORFSp6cUqTTzhnV4A++9ehw2wP
        zZ4M28gwT+l42wb1HsPiiAp3AoGACn5YrFvF8LoV1ETZ3D0OUFEVw6UrtHGiDc7g
        jbTUZDKIBi44kbMj0dg8hQNfkBssfalijvQggdYX3LhN3JOe5Pgnw9BFdVWdVgxr
        7XoQ6YWF3cnllv0tcpOb2mJmbD/579pkVGg6bmP9+ko1I7YMLtLUHdMFIKLR43dM
        fPIGAgECgYAnCXFRpFJ/x6hezPjbz5N9MYl/+3H3WCGsU3yPzQJucnN7Sptj1bBd
        yYx8rZ3HBI8Fltr/gBeO5WfiXsrO6F7UWD91B5L5mxJLx17bP9fGUKZacEUUFOXb
        gvhPlwBhnMPvDkV5NOowkO0VPE7BZ30Fd3wLpF/h1KxBr+NWbWL1Cw==
        -----END RSA PRIVATE KEY-----


    steps:
    - name: Download artifacts from S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        aws-key: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret: ${{ env.AWS_SECRET_ACCESS_KEY }}
        src: 's3://${{ env.AWS_S3_BUCKET }}/tasks/'
        dest: 'deploy/'

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ env.SSH_PRIVATE_KEY_PATH }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Install dependencies on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ec2-13-53-208-203.eu-north-1.compute.amazonaws.com "sudo apt-get update && sudo apt-get install -y python3-pip"
    
    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r deploy/* ubuntu@ec2-13-53-208-203.eu-north-1.compute.amazonaws.com:/path/to/deploy/
    
    - name: Restart Flask App on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ec2-13-53-208-203.eu-north-1.compute.amazonaws.com "cd /path/to/deploy/ && nohup python3 app.py > app.log 2>&1 &"
