name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_S3_BUCKET: todolist-1
      AWS_ACCESS_KEY_ID: AKIA2M72C4K3LN72TRR5
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: eu-north-1
      AWS_ROLE_TO_ASSUME: arn:aws:iam::715099660982:role/CICD-deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          aws-key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret: ${{ env.AWS_SECRET_ACCESS_KEY }}
          src: '.'
          dest: 's3://todolist-1/tasks/'

  deploy:
    runs-on: ubuntu-latest

    needs: build

    env:
      AWS_S3_BUCKET: todolist-1
      AWS_ACCESS_KEY_ID: AKIA2M72C4K3LN72TRR5
      AWS_SECRET_ACCESS_KEY: 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
      SSH_PRIVATE_KEY_PATH: 'todolist.pem'

    steps:
      - name: Download artifacts from S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          aws-key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret: ${{ env.AWS_SECRET_ACCESS_KEY }}
          src: 's3://${{ env.AWS_S3_BUCKET }}/tasks/'
          dest: 'deploy/'

      - name: Display Repository Content
        run: ls -la

      - name: Display SSH Private Key
        run: cat ${{ env.SSH_PRIVATE_KEY_PATH }}

      - name: Install dependencies on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ env.SSH_PRIVATE_KEY_PATH }}" ubuntu@ec2-13-53-208-203.eu-north-1.compute.amazonaws.com "sudo apt-get update && sudo apt-get install -y python3-pip"

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i "${{ env.SSH_PRIVATE_KEY_PATH }}" -r deploy/* ubuntu@ec2-13-53-208-203.eu-north-1.compute.amazonaws.com:/path/to/deploy/

      - name: Restart Flask App on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ env.SSH_PRIVATE_KEY_PATH }}" ubuntu@ec2-13-53-208-203.eu-north-1.compute.amazonaws.com "cd /path/to/deploy/ && nohup python3 app.py > app.log 2>&1 &"
