name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      AWS_S3_BUCKET: todolist-1
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install -r requirements.txt

    - name: Debug
      run: |
        echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
        echo "AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}"

    - name: Assume IAM Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 900

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        aws-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        src: '.'  
        dest: 's3://todolist-1/tasks/'

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Download artifacts from S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        aws-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        src: 's3://todolist-1/tasks/'
        dest: 'deploy/'

    - name: Install dependencies on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} ubuntu@ec2-13-53-208-203.eu-north-1.compute.amazonaws.com "sudo apt-get update && sudo apt-get install -y python3-pip"
    
    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} -r deploy/* ubuntu@ec2-13-53-208-203.eu-north-1.compute.amazonaws.com:/path/to/deploy/
    
    - name: Restart Flask App on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} ubuntu@ec2-13-53-208-203.eu-north-1.compute.amazonaws.com "cd /path/to/deploy/ && nohup python3 app.py > app.log 2>&1 &"
